# Generated by Django 4.1.3 on 2022-11-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.IntegerField(),
        ),
    ]
